### ISSUE TITLE
Add valentines day example

### ISSUE THREAD

**Issue by omwah** [omwah/GiftEvents#10]
Add valentine's day example to default events.yml:

```
valentines:
  date: 02-14
  belated: False
  gift:
    items:
      - { id: RED_ROSE, enchantments: {ARROW_INFINITE: 1} }
    name: "I love you!"
    message: "Happy Valentines Day %1$s, check your inventory for a gift!"
```
